Data Preprocessing part: https://www.kaggle.com/kendontcare11
I utilize Hyperopt for XGBoost, LightGBM, CatBoost
I utilize GridSearch for Ridge Regression
Finally: use Voting to ensemble 4 model

In [1]:
import sys
sys.path.insert(1, '/kaggle/input/featurecreation')
from features_creation import *

In [2]:
import pandas as pd
from sklearn.model_selection import KFold

In [3]:
#!pip install /kaggle/input/pip-install-lifelines/autograd-gamma-0.5.0
!pip install /kaggle/input/autogradgammawhl/other/default/1/autograd_gamma-0.4.2-py2.py3-none-any.whl
!pip install /kaggle/input/pip-install-lifelines/autograd-1.7.0-py3-none-any.whl
!pip install /kaggle/input/pip-install-lifelines/interface_meta-1.3.0-py3-none-any.whl
!pip install /kaggle/input/pip-install-lifelines/formulaic-1.0.2-py3-none-any.whl
!pip install /kaggle/input/pip-install-lifelines/lifelines-0.30.0-py3-none-any.whl

Processing /kaggle/input/autogradgammawhl/other/default/1/autograd_gamma-0.4.2-py2.py3-none-any.whl
Requirement already satisfied: autograd>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from autograd-gamma==0.4.2) (1.7.0)
Requirement already satisfied: scipy>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from autograd-gamma==0.4.2) (1.13.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from autograd>=1.2.0->autograd-gamma==0.4.2) (1.26.4)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.10/dist-packages (from numpy->autograd>=1.2.0->autograd-gamma==0.4.2) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.10/dist-packages (from numpy->autograd>=1.2.0->autograd-gamma==0.4.2) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.10/dist-packages (from numpy->autograd>=1.2.0->autograd-gamma==0.4.2) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.10/dist-packages (from numpy->autograd>=1.2.0->autograd-gamma==0.4.2) (2025.0.1)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.10/dist-packages (from numpy->autograd>=1.2.0->autograd-gamma==0.4.2) (2022.0.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.10/dist-packages (from numpy->autograd>=1.2.0->autograd-gamma==0.4.2) (2.4.1)
Requirement already satisfied: intel-openmp>=2024 in /usr/local/lib/python3.10/dist-packages (from mkl->numpy->autograd>=1.2.0->autograd-gamma==0.4.2) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.10/dist-packages (from mkl->numpy->autograd>=1.2.0->autograd-gamma==0.4.2) (2022.0.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.10/dist-packages (from tbb==2022.*->mkl->numpy->autograd>=1.2.0->autograd-gamma==0.4.2) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.10/dist-packages (from mkl_umath->numpy->autograd>=1.2.0->autograd-gamma==0.4.2) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.10/dist-packages (from intel-openmp>=2024->mkl->numpy->autograd>=1.2.0->autograd-gamma==0.4.2) (2024.2.0)
Installing collected packages: autograd-gamma
Successfully installed autograd-gamma-0.4.2
Processing /kaggle/input/pip-install-lifelines/autograd-1.7.0-py3-none-any.whl
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from autograd==1.7.0) (1.26.4)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.10/dist-packages (from numpy->autograd==1.7.0) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.10/dist-packages (from numpy->autograd==1.7.0) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.10/dist-packages (from numpy->autograd==1.7.0) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.10/dist-packages (from numpy->autograd==1.7.0) (2025.0.1)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.10/dist-packages (from numpy->autograd==1.7.0) (2022.0.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.10/dist-packages (from numpy->autograd==1.7.0) (2.4.1)
Requirement already satisfied: intel-openmp>=2024 in /usr/local/lib/python3.10/dist-packages (from mkl->numpy->autograd==1.7.0) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.10/dist-packages (from mkl->numpy->autograd==1.7.0) (2022.0.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.10/dist-packages (from tbb==2022.*->mkl->numpy->autograd==1.7.0) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.10/dist-packages (from mkl_umath->numpy->autograd==1.7.0) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.10/dist-packages (from intel-openmp>=2024->mkl->numpy->autograd==1.7.0) (2024.2.0)
autograd is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
Processing /kaggle/input/pip-install-lifelines/interface_meta-1.3.0-py3-none-any.whl
Installing collected packages: interface-meta
Successfully installed interface-meta-1.3.0
Processing /kaggle/input/pip-install-lifelines/formulaic-1.0.2-py3-none-any.whl
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from formulaic==1.0.2) (1.3.0)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.10/dist-packages (from formulaic==1.0.2) (1.26.4)
Requirement already satisfied: pandas>=1.0 in /usr/local/lib/python3.10/dist-packages (from formulaic==1.0.2) (2.2.3)
Requirement already satisfied: scipy>=1.6 in /usr/local/lib/python3.10/dist-packages (from formulaic==1.0.2) (1.13.1)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from formulaic==1.0.2) (4.12.2)
Requirement already satisfied: wrapt>=1.0 in /usr/local/lib/python3.10/dist-packages (from formulaic==1.0.2) (1.17.0)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.10/dist-packages (from numpy>=1.16.5->formulaic==1.0.2) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.10/dist-packages (from numpy>=1.16.5->formulaic==1.0.2) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.10/dist-packages (from numpy>=1.16.5->formulaic==1.0.2) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.10/dist-packages (from numpy>=1.16.5->formulaic==1.0.2) (2025.0.1)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.10/dist-packages (from numpy>=1.16.5->formulaic==1.0.2) (2022.0.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.10/dist-packages (from numpy>=1.16.5->formulaic==1.0.2) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0->formulaic==1.0.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0->formulaic==1.0.2) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0->formulaic==1.0.2) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0->formulaic==1.0.2) (1.17.0)
Requirement already satisfied: intel-openmp>=2024 in /usr/local/lib/python3.10/dist-packages (from mkl->numpy>=1.16.5->formulaic==1.0.2) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.10/dist-packages (from mkl->numpy>=1.16.5->formulaic==1.0.2) (2022.0.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.10/dist-packages (from tbb==2022.*->mkl->numpy>=1.16.5->formulaic==1.0.2) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.10/dist-packages (from mkl_umath->numpy>=1.16.5->formulaic==1.0.2) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.10/dist-packages (from intel-openmp>=2024->mkl->numpy>=1.16.5->formulaic==1.0.2) (2024.2.0)
Installing collected packages: formulaic
Successfully installed formulaic-1.0.2
Processing /kaggle/input/pip-install-lifelines/lifelines-0.30.0-py3-none-any.whl
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from lifelines==0.30.0) (1.26.4)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from lifelines==0.30.0) (1.13.1)
Requirement already satisfied: pandas>=2.1 in /usr/local/lib/python3.10/dist-packages (from lifelines==0.30.0) (2.2.3)
Requirement already satisfied: matplotlib>=3.0 in /usr/local/lib/python3.10/dist-packages (from lifelines==0.30.0) (3.7.5)
Requirement already satisfied: autograd>=1.5 in /usr/local/lib/python3.10/dist-packages (from lifelines==0.30.0) (1.7.0)
Requirement already satisfied: autograd-gamma>=0.3 in /usr/local/lib/python3.10/dist-packages (from lifelines==0.30.0) (0.4.2)
Requirement already satisfied: formulaic>=0.2.2 in /usr/local/lib/python3.10/dist-packages (from lifelines==0.30.0) (1.0.2)
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from formulaic>=0.2.2->lifelines==0.30.0) (1.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from formulaic>=0.2.2->lifelines==0.30.0) (4.12.2)
Requirement already satisfied: wrapt>=1.0 in /usr/local/lib/python3.10/dist-packages (from formulaic>=0.2.2->lifelines==0.30.0) (1.17.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0->lifelines==0.30.0) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0->lifelines==0.30.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0->lifelines==0.30.0) (4.55.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0->lifelines==0.30.0) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0->lifelines==0.30.0) (24.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0->lifelines==0.30.0) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0->lifelines==0.30.0) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0->lifelines==0.30.0) (2.9.0.post0)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.10/dist-packages (from numpy>=1.14.0->lifelines==0.30.0) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.10/dist-packages (from numpy>=1.14.0->lifelines==0.30.0) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.10/dist-packages (from numpy>=1.14.0->lifelines==0.30.0) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.10/dist-packages (from numpy>=1.14.0->lifelines==0.30.0) (2025.0.1)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.10/dist-packages (from numpy>=1.14.0->lifelines==0.30.0) (2022.0.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.10/dist-packages (from numpy>=1.14.0->lifelines==0.30.0) (2.4.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.1->lifelines==0.30.0) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.1->lifelines==0.30.0) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0->lifelines==0.30.0) (1.17.0)
Requirement already satisfied: intel-openmp>=2024 in /usr/local/lib/python3.10/dist-packages (from mkl->numpy>=1.14.0->lifelines==0.30.0) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.10/dist-packages (from mkl->numpy>=1.14.0->lifelines==0.30.0) (2022.0.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.10/dist-packages (from tbb==2022.*->mkl->numpy>=1.14.0->lifelines==0.30.0) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.10/dist-packages (from mkl_umath->numpy>=1.14.0->lifelines==0.30.0) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.10/dist-packages (from intel-openmp>=2024->mkl->numpy>=1.14.0->lifelines==0.30.0) (2024.2.0)
Installing collected packages: lifelines
Successfully installed lifelines-0.30.0

In [4]:
import pandas as pd
import pandas.api.types
import numpy as np
from lifelines.utils import concordance_index

class ParticipantVisibleError(Exception):
    pass


def score(solution: pd.DataFrame, submission: pd.DataFrame, row_id_column_name: str) -> float:
    """
    >>> import pandas as pd
    >>> row_id_column_name = "id"
    >>> y_pred = {'prediction': {0: 1.0, 1: 0.0, 2: 1.0}}
    >>> y_pred = pd.DataFrame(y_pred)
    >>> y_pred.insert(0, row_id_column_name, range(len(y_pred)))
    >>> y_true = { 'efs': {0: 1.0, 1: 0.0, 2: 0.0}, 'efs_time': {0: 25.1234,1: 250.1234,2: 2500.1234}, 'race_group': {0: 'race_group_1', 1: 'race_group_1', 2: 'race_group_1'}}
    >>> y_true = pd.DataFrame(y_true)
    >>> y_true.insert(0, row_id_column_name, range(len(y_true)))
    >>> score(y_true.copy(), y_pred.copy(), row_id_column_name)
    0.75
    """
    
    del solution[row_id_column_name]
    del submission[row_id_column_name]
    
    event_label = 'efs'
    interval_label = 'efs_time'
    prediction_label = 'prediction'
    for col in submission.columns:
        if not pandas.api.types.is_numeric_dtype(submission[col]):
            raise ParticipantVisibleError(f'Submission column {col} must be a number')
    # Merging solution and submission dfs on ID
    merged_df = pd.concat([solution, submission], axis=1)
    merged_df.reset_index(inplace=True)
    merged_df_race_dict = dict(merged_df.groupby(['race_group']).groups)
    metric_list = []
    for race in merged_df_race_dict.keys():
        # Retrieving values from y_test based on index
        indices = sorted(merged_df_race_dict[race])
        merged_df_race = merged_df.iloc[indices]
        # Calculate the concordance index
        c_index_race = concordance_index(
                        merged_df_race[interval_label],
                        -merged_df_race[prediction_label],
                        merged_df_race[event_label])
        metric_list.append(c_index_race)
    return float(np.mean(metric_list)-np.sqrt(np.var(metric_list)))

In [5]:
from lifelines import KaplanMeierFitter, NelsonAalenFitter
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import time
import warnings
warnings.filterwarnings('ignore')
from sklearn import preprocessing
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.base import BaseEstimator, TransformerMixin

## Data Preprocessing

In [6]:
train_data = pd.read_csv('/kaggle/input/equity-post-HCT-survival-predictions/train.csv')
test_data = pd.read_csv('/kaggle/input/equity-post-HCT-survival-predictions/test.csv')

In [7]:
old_train_data = train_data.copy()
old_test_data = test_data.copy()

In [8]:
ID_col = 'ID'
y_train_kmf = train_data['KaplanMeier'] = KaplanMeierFitter().fit(train_data['efs_time'], train_data['efs']).survival_function_at_times(train_data['efs_time']).values

In [9]:
RMV = ["ID","efs","efs_time",'KaplanMeier']
FEATURES = [c for c in train_data.columns if not c in RMV]
print(f"There are {len(FEATURES)} FEATURES: {FEATURES}")

There are 57 FEATURES: ['dri_score', 'psych_disturb', 'cyto_score', 'diabetes', 'hla_match_c_high', 'hla_high_res_8', 'tbi_status', 'arrhythmia', 'hla_low_res_6', 'graft_type', 'vent_hist', 'renal_issue', 'pulm_severe', 'prim_disease_hct', 'hla_high_res_6', 'cmv_status', 'hla_high_res_10', 'hla_match_dqb1_high', 'tce_imm_match', 'hla_nmdp_6', 'hla_match_c_low', 'rituximab', 'hla_match_drb1_low', 'hla_match_dqb1_low', 'prod_type', 'cyto_score_detail', 'conditioning_intensity', 'ethnicity', 'year_hct', 'obesity', 'mrd_hct', 'in_vivo_tcd', 'tce_match', 'hla_match_a_high', 'hepatic_severe', 'donor_age', 'prior_tumor', 'hla_match_b_low', 'peptic_ulcer', 'age_at_hct', 'hla_match_a_low', 'gvhd_proph', 'rheum_issue', 'sex_match', 'hla_match_b_high', 'race_group', 'comorbidity_score', 'karnofsky_score', 'hepatic_mild', 'tce_div_match', 'donor_related', 'melphalan_dose', 'hla_low_res_8', 'cardiac', 'hla_match_drb1_high', 'pulm_moderate', 'hla_low_res_10']

In [10]:
hct_ci_mapping = {
    "arrhythmia": {"No": 0, "Not done": 0, "Yes": 1},  
    "cardiac": {"No": 0, "Not done": 0, "Yes": 1}, 
    "diabetes": {"No": 0, "Not done": 0, "Yes": 1},  
    "hepatic_mild": {"No": 0, "Not done": 0, "Yes": 1},
    "hepatic_severe": {"No": 0, "Not done": 0, "Yes": 3},
    "psych_disturb": {"No": 0, "Not done": 0, "Yes": 1}, 
    "obesity": {"No": 0, "Not done": 0, "Yes": 1}, 
    "rheum_issue": {"No": 0, "Not done": 0, "Yes": 2},
    "peptic_ulcer": {"No": 0, "Not done": 0, "Yes": 2},  
    "renal_issue": {"No": 0, "Not done": 0, "Yes": 2}, 
    "prior_tumor": {"No": 0, "Not done": 0, "Yes": 3}, 
    "pulm_moderate": {"No": 0, "Not done": 0, "Yes": 2}, 
    "pulm_severe": {"No": 0, "Not done": 0, "Yes": 3},  
}
def calculate_hct_ci_score(row, mapping):
        """
        This function calculates the hct_ci score
    
        Args:
            row (pd.Series): Patient Clinical Data
            mapping (dict): HCT-CI score mapping
    
        Returns:
            int: HCT-CI score
        """
    
        score = 0
    
        if "hepatic_severe" in row and row["hepatic_severe"] == "Yes":
            score += mapping["hepatic_severe"]["Yes"]
        elif "hepatic_mild" in row and row["hepatic_mild"] == "Yes":
            score += mapping["hepatic_mild"]["Yes"]
        if "pulm_moderate" in row and row["pulm_moderate"] == "Yes":
            score += mapping["pulm_moderate"]["Yes"]
        elif "pulm_severe" in row and row["pulm_severe"] == "Yes":
            score += mapping["pulm_severe"]["Yes"]
    
        # Other Conditions
        for condition, mapping_values in mapping.items():
            if condition not in ["hepatic_mild", "hepatic_severe","pulm_moderate", "pulm_severe"] and condition in row:
                score += mapping_values.get(row[condition], 0)
    
        return score

In [11]:
def cat2num(df):
    df['conditioning_intensity'] = df['conditioning_intensity'].map({
    'NMA': 1, 
    'RIC': 2,
    'MAC': 3,
    'TBD': None,
    'No drugs reported': None,
    'N/A, F(pre-TED) not submitted': None})
    
    df['tbi_status'] = df['tbi_status'].map({
    'No TBI': 0, 
    'TBI +- Other, <=cGy': 1,
    'TBI +- Other, -cGy, fractionated': 2,
    'TBI + Cy +- Other': 3,
    'TBI +- Other, -cGy, single': 4,
    'TBI +- Other, >cGy': 5,
    'TBI +- Other, unknown dose': None})
    
    df['dri_score'] = df['dri_score'].map({
    'Low': 1, 
    'Intermediate': 2,
    'Intermediate - TED AML case <missing cytogenetics': 3,
    'High': 4,
    'High - TED AML case <missing cytogenetics': 5,
    'Very High': 6,
    'N/A - pediatric': -3,
    'N/A - non-malignant indication': -1,
    'TBD cytogenetics': -2,
    'N/A - disease not classifiable': -4,
    'Missing disease status': 0})
    
    df['cyto_score'] = df['cyto_score'].map({
    'Poor': 4,
    'Normal': 3,
    'Intermediate': 2,
    'Favorable': 1,
    'TBD': -1,
    'Other': -2,
    'Not tested': None})
    
    df['cyto_score_detail'] = df['cyto_score_detail'].map({
    'Poor': 3, 
    'Intermediate': 2,
    'Favorable': 1,
    'TBD': -1,
    'Not tested': None})
    
    return df

In [12]:
def fill_hla_combined_low(row):
    if np.isnan(row['hla_combined_low']): 
        components = [
            row['hla_match_drb1_low'], row['hla_match_dqb1_low'], 
            row['hla_match_a_low'], row['hla_match_b_low'], row['hla_match_c_low']
        ]
        if all([not np.isnan(x) for x in components]):
            return sum(components)
        else:
            if not np.isnan(row['hla_low_res_8']) and not np.isnan(row['hla_match_dqb1_low']):
                return row['hla_low_res_8'] + row['hla_match_dqb1_low']
            elif not np.isnan(row['hla_low_res_6']): 
                components_6 = [
                    row['hla_match_dqb1_low'], row['hla_match_c_low']
                ]
                if all([not np.isnan(x) for x in components_6]):
                    return row['hla_low_res_6'] + sum(components_6)
                else: 
                    return sum([x for x in components if not np.isnan(x)])
    return row['hla_combined_low']

In [13]:
def add_features(df):
    df["hct_ci_score"] = df.apply(lambda row: calculate_hct_ci_score(row, hct_ci_mapping), axis=1)
    df['donor_recipient_age_diff'] = abs(df['donor_age'] - df['age_at_hct'])
    df = cat2num(df)
    df['hla_combined_low'] = df['hla_low_res_10']
    df['hla_combined_low'] = df.apply(fill_hla_combined_low, axis=1)
    df['hla_match_ratio'] = (df['hla_high_res_8'] + df['hla_low_res_8']) / 16
    df['years_since_2000'] = df['year_hct'] - 2000
    df['null_count'] = df.isnull().sum(axis=1)
    df['ci_score_danger'] = df['hct_ci_score'].apply(lambda x: 2 if x >= 3 else 1 if x >= 1 else 0)
    return df

train_data = add_features(train_data)
test_data = add_features(test_data)

In [14]:
FEATURES += ["hct_ci_score", 'donor_recipient_age_diff', "hla_combined_low", "hla_match_ratio", 
             "years_since_2000", "null_count","ci_score_danger"]

In [15]:
train_data.head()

,ID,dri_score,psych_disturb,cyto_score,diabetes,hla_match_c_high,hla_high_res_8,tbi_status,arrhythmia,hla_low_res_6,...,efs,efs_time,KaplanMeier,hct_ci_score,donor_recipient_age_diff,hla_combined_low,hla_match_ratio,years_since_2000,null_count,ci_score_danger
0,0,-1.0,No,NaN,No,NaN,NaN,0.0,No,6.0,...,0.0,42.356,0.458687,0,NaN,10.0,NaN,16,13,0
1,1,2.0,No,2.0,No,2.0,8.0,5.0,No,6.0,...,1.0,4.672,0.847759,2,28.585,10.0,1.0,8,0,1
2,2,-1.0,No,NaN,No,2.0,8.0,0.0,No,6.0,...,0.0,19.793,0.462424,0,NaN,10.0,1.0,19,7,0
3,3,4.0,No,2.0,No,2.0,8.0,0.0,No,6.0,...,0.0,102.349,0.456661,1,14.015,10.0,1.0,9,0,1
4,4,4.0,No,NaN,No,2.0,8.0,0.0,No,6.0,...,0.0,16.223,0.464674,0,27.070,10.0,1.0,18,5,0

In [16]:
del train_data['year_hct']
del test_data['year_hct']

In [17]:
FEATURES = ['dri_score',
 'psych_disturb',
 'cyto_score',
 'diabetes',
 'hla_match_c_high',
 'hla_high_res_8',
 'tbi_status',
 'arrhythmia',
 'hla_low_res_6',
 'graft_type',
 'vent_hist',
 'renal_issue',
 'pulm_severe',
 'prim_disease_hct',
 'hla_high_res_6',
 'cmv_status',
 'hla_high_res_10',
 'hla_match_dqb1_high',
 'tce_imm_match',
 'hla_nmdp_6',
 'hla_match_c_low',
 'rituximab',
 'hla_match_drb1_low',
 'hla_match_dqb1_low',
 'prod_type',
 'cyto_score_detail',
 'conditioning_intensity',
 'ethnicity',
 'obesity',
 'mrd_hct',
 'in_vivo_tcd',
 'tce_match',
 'hla_match_a_high',
 'hepatic_severe',
 'donor_age',
 'prior_tumor',
 'hla_match_b_low',
 'peptic_ulcer',
 'age_at_hct',
 'hla_match_a_low',
 'gvhd_proph',
 'rheum_issue',
 'sex_match',
 'hla_match_b_high',
 'race_group',
 'comorbidity_score',
 'karnofsky_score',
 'hepatic_mild',
 'tce_div_match',
 'donor_related',
 'melphalan_dose',
 'hla_low_res_8',
 'cardiac',
 'hla_match_drb1_high',
 'pulm_moderate',
 'hla_low_res_10',
 'hct_ci_score',
 'donor_recipient_age_diff',
 'hla_combined_low',
 'hla_match_ratio',
 'years_since_2000',
 'null_count',
 'ci_score_danger']

In [18]:
numeric = ['age_at_hct','year_hct','donor_age','null_count','hla_match_ratio','years_since_2000','donor_recipient_age_diff']
#numeric = ['age_at_hct','donor_age','null_count','donor_recipient_age_diff']
CATS = []
for c in FEATURES:
    if c not in numeric:
        CATS.append(c)
        train_data[c] = train_data[c].fillna("NAN")
        test_data[c] = test_data[c].fillna("NAN")
print(f"In these features, there are {len(CATS)} CATEGORICAL FEATURES: {CATS}")

In these features, there are 57 CATEGORICAL FEATURES: ['dri_score', 'psych_disturb', 'cyto_score', 'diabetes', 'hla_match_c_high', 'hla_high_res_8', 'tbi_status', 'arrhythmia', 'hla_low_res_6', 'graft_type', 'vent_hist', 'renal_issue', 'pulm_severe', 'prim_disease_hct', 'hla_high_res_6', 'cmv_status', 'hla_high_res_10', 'hla_match_dqb1_high', 'tce_imm_match', 'hla_nmdp_6', 'hla_match_c_low', 'rituximab', 'hla_match_drb1_low', 'hla_match_dqb1_low', 'prod_type', 'cyto_score_detail', 'conditioning_intensity', 'ethnicity', 'obesity', 'mrd_hct', 'in_vivo_tcd', 'tce_match', 'hla_match_a_high', 'hepatic_severe', 'prior_tumor', 'hla_match_b_low', 'peptic_ulcer', 'hla_match_a_low', 'gvhd_proph', 'rheum_issue', 'sex_match', 'hla_match_b_high', 'race_group', 'comorbidity_score', 'karnofsky_score', 'hepatic_mild', 'tce_div_match', 'donor_related', 'melphalan_dose', 'hla_low_res_8', 'cardiac', 'hla_match_drb1_high', 'pulm_moderate', 'hla_low_res_10', 'hct_ci_score', 'hla_combined_low', 'ci_score_danger']

In [19]:
combined = pd.concat([train_data,test_data],axis=0,ignore_index=True)
#print("Combined data shape:", combined.shape )

# LABEL ENCODE CATEGORICAL FEATURES
print("We LABEL ENCODE the CATEGORICAL FEATURES: ",end="")
for c in FEATURES:

    # LABEL ENCODE CATEGORICAL AND CONVERT TO INT32 CATEGORY
    if c in CATS:
        print(f"{c}, ",end="")
        combined[c],_ = combined[c].factorize()
        combined[c] -= combined[c].min()
        combined[c] = combined[c].astype("int32")
        combined[c] = combined[c].astype("category")
        
    # REDUCE PRECISION OF NUMERICAL TO 32BIT TO SAVE MEMORY
    else:
        if combined[c].dtype=="float64":
            combined[c] = combined[c].astype("float32")
        if combined[c].dtype=="int64":
            combined[c] = combined[c].astype("int32")

# for c in cat2num:
#     combined[c] = combined[c].astype("int32")

train_data = combined.iloc[:len(train_data)].copy()
test_data = combined.iloc[len(train_data):].reset_index(drop=True).copy()

We LABEL ENCODE the CATEGORICAL FEATURES: dri_score, psych_disturb, cyto_score, diabetes, hla_match_c_high, hla_high_res_8, tbi_status, arrhythmia, hla_low_res_6, graft_type, vent_hist, renal_issue, pulm_severe, prim_disease_hct, hla_high_res_6, cmv_status, hla_high_res_10, hla_match_dqb1_high, tce_imm_match, hla_nmdp_6, hla_match_c_low, rituximab, hla_match_drb1_low, hla_match_dqb1_low, prod_type, cyto_score_detail, conditioning_intensity, ethnicity, obesity, mrd_hct, in_vivo_tcd, tce_match, hla_match_a_high, hepatic_severe, prior_tumor, hla_match_b_low, peptic_ulcer, hla_match_a_low, gvhd_proph, rheum_issue, sex_match, hla_match_b_high, race_group, comorbidity_score, karnofsky_score, hepatic_mild, tce_div_match, donor_related, melphalan_dose, hla_low_res_8, cardiac, hla_match_drb1_high, pulm_moderate, hla_low_res_10, hct_ci_score, hla_combined_low, ci_score_danger,

In [20]:
ID_col = 'ID'
target = 'KaplanMeier'
del train_data['efs_time']
del train_data['efs']

In [21]:
del test_data['efs_time']
del test_data['efs']
del test_data['KaplanMeier']

In [22]:
train_data.shape

(28800, 65)

In [23]:
test_data.shape

(3, 64)

In [24]:
train_cont = train_data[['age_at_hct','donor_age','null_count','hla_match_ratio','years_since_2000','donor_recipient_age_diff']]
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
train_newcont = scaler.fit_transform(train_cont.values)
train_transform_cont = pd.DataFrame(train_newcont, index=train_cont.index, columns=train_cont.columns)

In [25]:
train_data['age_at_hct'] = train_transform_cont['age_at_hct']
train_data['donor_age'] = train_transform_cont['donor_age'] 
train_data['null_count']= train_transform_cont['null_count'] 
train_data['hla_match_ratio']= train_transform_cont['hla_match_ratio'] 
train_data['years_since_2000']= train_transform_cont['years_since_2000'] 
train_data['donor_recipient_age_diff']= train_transform_cont['donor_recipient_age_diff']

In [26]:
test_cont = test_data[['age_at_hct','donor_age','null_count','hla_match_ratio','years_since_2000','donor_recipient_age_diff']]
test_newcont = scaler.transform(test_cont.values)
test_transform_cont = pd.DataFrame(test_newcont, index=test_cont.index, columns=test_cont.columns)

In [27]:
test_data['age_at_hct'] = test_transform_cont['age_at_hct']
test_data['donor_age'] = test_transform_cont['donor_age'] 
test_data['null_count']= test_transform_cont['null_count'] 
test_data['hla_match_ratio']= test_transform_cont['hla_match_ratio'] 
test_data['years_since_2000']= test_transform_cont['years_since_2000'] 
test_data['donor_recipient_age_diff']= test_transform_cont['donor_recipient_age_diff']

In [28]:
train_data['donor_age'] = train_data['donor_age'].fillna(train_data['donor_age'].mean())
train_data['hla_match_ratio'] = train_data['hla_match_ratio'].fillna(train_data['hla_match_ratio'].mean())
train_data['donor_recipient_age_diff'] = train_data['donor_recipient_age_diff'].fillna(train_data['donor_recipient_age_diff'].mean())

In [29]:
test_data['donor_age'] = test_data['donor_age'].fillna(test_data['donor_age'].mean())
test_data['hla_match_ratio'] = test_data['hla_match_ratio'].fillna(test_data['hla_match_ratio'].mean())
test_data['donor_recipient_age_diff'] = test_data['donor_recipient_age_diff'].fillna(test_data['donor_recipient_age_diff'].mean())

In [30]:
X_train = train_data.drop(columns=[ID_col, target]).copy()
X_test = test_data.drop(columns=[ID_col]).copy()
y_train = train_data['KaplanMeier'].copy()

In [31]:
CATS = ['dri_score',
 'psych_disturb',
 'cyto_score',
 'diabetes',
 'hla_match_c_high',
 'hla_high_res_8',
 'tbi_status',
 'arrhythmia',
 'hla_low_res_6',
 'graft_type',
 'vent_hist',
 'renal_issue',
 'pulm_severe',
 'prim_disease_hct',
 'hla_high_res_6',
 'cmv_status',
 'hla_high_res_10',
 'hla_match_dqb1_high',
 'tce_imm_match',
 'hla_nmdp_6',
 'hla_match_c_low',
 'rituximab',
 'hla_match_drb1_low',
 'hla_match_dqb1_low',
 'prod_type',
 'cyto_score_detail',
 'conditioning_intensity',
 'ethnicity',
 'obesity',
 'mrd_hct',
 'in_vivo_tcd',
 'tce_match',
 'hla_match_a_high',
 'hepatic_severe',
 'prior_tumor',
 'hla_match_b_low',
 'peptic_ulcer',
 'hla_match_a_low',
 'gvhd_proph',
 'rheum_issue',
 'sex_match',
 'hla_match_b_high',
 'race_group',
 'comorbidity_score',
 'karnofsky_score',
 'hepatic_mild',
 'tce_div_match',
 'donor_related',
 'melphalan_dose',
 'hla_low_res_8',
 'cardiac',
 'hla_match_drb1_high',
 'pulm_moderate',
 'hla_low_res_10',
 'hct_ci_score',
 'hla_combined_low',
 'ci_score_danger']

In [32]:
CATS

['dri_score',
 'psych_disturb',
 'cyto_score',
 'diabetes',
 'hla_match_c_high',
 'hla_high_res_8',
 'tbi_status',
 'arrhythmia',
 'hla_low_res_6',
 'graft_type',
 'vent_hist',
 'renal_issue',
 'pulm_severe',
 'prim_disease_hct',
 'hla_high_res_6',
 'cmv_status',
 'hla_high_res_10',
 'hla_match_dqb1_high',
 'tce_imm_match',
 'hla_nmdp_6',
 'hla_match_c_low',
 'rituximab',
 'hla_match_drb1_low',
 'hla_match_dqb1_low',
 'prod_type',
 'cyto_score_detail',
 'conditioning_intensity',
 'ethnicity',
 'obesity',
 'mrd_hct',
 'in_vivo_tcd',
 'tce_match',
 'hla_match_a_high',
 'hepatic_severe',
 'prior_tumor',
 'hla_match_b_low',
 'peptic_ulcer',
 'hla_match_a_low',
 'gvhd_proph',
 'rheum_issue',
 'sex_match',
 'hla_match_b_high',
 'race_group',
 'comorbidity_score',
 'karnofsky_score',
 'hepatic_mild',
 'tce_div_match',
 'donor_related',
 'melphalan_dose',
 'hla_low_res_8',
 'cardiac',
 'hla_match_drb1_high',
 'pulm_moderate',
 'hla_low_res_10',
 'hct_ci_score',
 'hla_combined_low',
 'ci_score_danger']

In [33]:
X_train.shape

(28800, 63)

In [34]:
X_test.shape

(3, 63)

## LightGBM

In [35]:
import lightgbm as lgb
from lightgbm import LGBMClassifier,LGBMRegressor

In [36]:
from sklearn.model_selection import KFold

In [37]:
train_data['y'] = y_train

In [38]:
from sklearn.model_selection import KFold
FOLDS = 10
kf = KFold(n_splits=FOLDS, shuffle=True, random_state=42)
    
oof_lgb = np.zeros(len(train_data))
pred_lgb = np.zeros(len(test_data))

for i, (train_index, test_index) in enumerate(kf.split(train_data)):

    print("#"*25)
    print(f"### Fold {i+1}")
    print("#"*25)
    
    x_train = train_data.loc[train_index,FEATURES].copy()
    y_train = train_data.loc[train_index,"y"]    
    x_valid = train_data.loc[test_index,FEATURES].copy()
    y_valid = train_data.loc[test_index,"y"]
    x_test = test_data[FEATURES].copy()

    model_lgb = LGBMRegressor(num_boost_round = 6000,verbose=-1,bagging_fraction=0.9496219531394654,bagging_freq=1,boosting_type= 'gbdt',colsample_bynode=0.49190952114458525,colsample_bytree=0.9276799260625302,feature_fraction=0.6237476443614289,importance_type='gain',lambda_l1=0.3307453595868796,lambda_l2=0.3748389968255914,learning_rate=0.014357619575271343,
max_depth=5,min_data_in_leaf=135,num_leaves=20)
   
    model_lgb.fit(
        x_train, y_train,
        eval_set=[(x_valid, y_valid)],
    )
    
    # INFER OOF
    oof_lgb[test_index] = model_lgb.predict(x_valid)
    # INFER TEST
    pred_lgb += model_lgb.predict(x_test)

# COMPUTE AVERAGE TEST PREDS
pred_lgb /= FOLDS

#########################
### Fold 1
#########################
#########################
### Fold 2
#########################
#########################
### Fold 3
#########################
#########################
### Fold 4
#########################
#########################
### Fold 5
#########################
#########################
### Fold 6
#########################
#########################
### Fold 7
#########################
#########################
### Fold 8
#########################
#########################
### Fold 9
#########################
#########################
### Fold 10
#########################

In [39]:
y_true = old_train_data[["ID","efs","efs_time","race_group"]].copy()
y_pred = train_data[["ID"]].copy()
y_pred["prediction"] = oof_lgb
m = score(y_true.copy(), y_pred.copy(), "ID")
print(f"\nOverall CV for LightGBM KaplanMeier =",m)

Overall CV for LightGBM KaplanMeier = 0.6671215434395378

In [40]:
train_data["efs_time2"] = old_train_data.efs_time.copy()
train_data.loc[old_train_data.efs==0,"efs_time2"] *= -1

In [41]:
from sklearn.model_selection import KFold
FOLDS = 10
kf = KFold(n_splits=FOLDS, shuffle=True, random_state=42)
    
oof_lgb_cox = np.zeros(len(train_data))
pred_lgb_cox = np.zeros(len(test_data))

for i, (train_index, test_index) in enumerate(kf.split(train_data)):

    print("#"*25)
    print(f"### Fold {i+1}")
    print("#"*25)
    
    x_train = train_data.loc[train_index,FEATURES].copy()
    y_train = train_data.loc[train_index,"efs_time2"]    
    x_valid = train_data.loc[test_index,FEATURES].copy()
    y_valid = train_data.loc[test_index,"efs_time2"]
    x_test = test_data[FEATURES].copy()

    model_lgb_cox = LGBMRegressor(num_boost_round = 6000,verbose=-1,bagging_fraction=0.9496219531394654,bagging_freq=1,boosting_type= 'gbdt',colsample_bynode=0.49190952114458525,colsample_bytree=0.9276799260625302,feature_fraction=0.6237476443614289,importance_type='gain',lambda_l1=0.3307453595868796,lambda_l2=0.3748389968255914,learning_rate=0.014357619575271343,
max_depth=5,min_data_in_leaf=135,num_leaves=20)
   
    model_lgb_cox.fit(
        x_train, y_train,
        eval_set=[(x_valid, y_valid)],
    )
    
    # INFER OOF
    oof_lgb_cox[test_index] = model_lgb_cox.predict(x_valid)
    # INFER TEST
    pred_lgb_cox += model_lgb_cox.predict(x_test)

# COMPUTE AVERAGE TEST PREDS
pred_lgb_cox /= FOLDS

#########################
### Fold 1
#########################
#########################
### Fold 2
#########################
#########################
### Fold 3
#########################
#########################
### Fold 4
#########################
#########################
### Fold 5
#########################
#########################
### Fold 6
#########################
#########################
### Fold 7
#########################
#########################
### Fold 8
#########################
#########################
### Fold 9
#########################
#########################
### Fold 10
#########################

In [42]:
y_true = old_train_data[["ID","efs","efs_time","race_group"]].copy()
y_pred = train_data[["ID"]].copy()
y_pred["prediction"] = oof_lgb_cox
m = score(y_true.copy(), y_pred.copy(), "ID")
print(f"\nOverall CV for LightGBM Survival:Cox =",m)

Overall CV for LightGBM Survival:Cox = 0.6125893873839398

## XGBoost

In [43]:
from sklearn.model_selection import KFold
from xgboost import XGBRegressor, XGBClassifier
import xgboost as xgb
print("Using XGBoost version",xgb.__version__)

Using XGBoost version 2.0.3

In [44]:
import time
start = time.time()

FOLDS = 10
kf = KFold(n_splits=FOLDS, shuffle=True, random_state=42)
    
oof_xgb = np.zeros(len(train_data))
pred_xgb = np.zeros(len(test_data))

for i, (train_index, test_index) in enumerate(kf.split(train_data)):

    print("#"*25)
    print(f"### Fold {i+1}")
    print("#"*25)
    
    x_train = train_data.loc[train_index,FEATURES].copy()
    y_train = train_data.loc[train_index,"y"]
    x_valid = train_data.loc[test_index,FEATURES].copy()
    y_valid = train_data.loc[test_index,"y"]
    x_test = test_data[FEATURES].copy()

    model_xgb = XGBRegressor(num_boost_round =6000,enable_categorical=True,booster='gbtree',colsample_bynode=0.85,colsample_bytree=0.6,eta=0.01,reg_lambda=2.0,max_depth=7,min_child_weight=40,rate_drop=0.2,subsample=0.9)
    model_xgb.fit(
        x_train, y_train,
        eval_set=[(x_valid, y_valid)],  
        verbose=500 
    )

    # INFER OOF
    oof_xgb[test_index] = model_xgb.predict(x_valid)
    # INFER TEST
    pred_xgb += model_xgb.predict(x_test)

# COMPUTE AVERAGE TEST PREDS
pred_xgb /= FOLDS

end = time.time()
print(end - start)

#########################
### Fold 1
#########################
[0]	validation_0-rmse:0.17785
[99]	validation_0-rmse:0.16706
#########################
### Fold 2
#########################
[0]	validation_0-rmse:0.17364
[99]	validation_0-rmse:0.16216
#########################
### Fold 3
#########################
[0]	validation_0-rmse:0.17738
[99]	validation_0-rmse:0.16559
#########################
### Fold 4
#########################
[0]	validation_0-rmse:0.17935
[99]	validation_0-rmse:0.16765
#########################
### Fold 5
#########################
[0]	validation_0-rmse:0.17380
[99]	validation_0-rmse:0.16357
#########################
### Fold 6
#########################
[0]	validation_0-rmse:0.17761
[99]	validation_0-rmse:0.16626
#########################
### Fold 7
#########################
[0]	validation_0-rmse:0.17862
[99]	validation_0-rmse:0.16785
#########################
### Fold 8
#########################
[0]	validation_0-rmse:0.17472
[99]	validation_0-rmse:0.16397
#########################
### Fold 9
#########################
[0]	validation_0-rmse:0.17661
[99]	validation_0-rmse:0.16616
#########################
### Fold 10
#########################
[0]	validation_0-rmse:0.17536
[99]	validation_0-rmse:0.16445
9.847608089447021

In [45]:
y_true = old_train_data[["ID","efs","efs_time","race_group"]].copy()
y_pred = train_data[["ID"]].copy()
y_pred["prediction"] = oof_xgb
m = score(y_true.copy(), y_pred.copy(), "ID")
print(f"\nOverall CV for XGBoost KaplanMeier =",m)

Overall CV for XGBoost KaplanMeier = 0.6583467577860218

In [46]:
import time
start = time.time()

FOLDS = 10
kf = KFold(n_splits=FOLDS, shuffle=True, random_state=42)
    
oof_xgb_cox = np.zeros(len(train_data))
pred_xgb_cox = np.zeros(len(test_data))

for i, (train_index, test_index) in enumerate(kf.split(train_data)):

    print("#"*25)
    print(f"### Fold {i+1}")
    print("#"*25)
    
    x_train = train_data.loc[train_index,FEATURES].copy()
    y_train = train_data.loc[train_index,"efs_time2"]
    x_valid = train_data.loc[test_index,FEATURES].copy()
    y_valid = train_data.loc[test_index,"efs_time2"]
    x_test = test_data[FEATURES].copy()

    model_xgb_cox = XGBRegressor(num_boost_round =6000,enable_categorical=True,booster='gbtree',colsample_bynode=0.85,colsample_bytree=0.6,eta=0.01,reg_lambda=2.0,max_depth=7,min_child_weight=40,rate_drop=0.2,subsample=0.9)
    model_xgb_cox.fit(
        x_train, y_train,
        eval_set=[(x_valid, y_valid)],  
        verbose=500 
    )

    # INFER OOF
    oof_xgb_cox[test_index] = model_xgb_cox.predict(x_valid)
    # INFER TEST
    pred_xgb_cox += model_xgb_cox.predict(x_test)

# COMPUTE AVERAGE TEST PREDS
pred_xgb_cox /= FOLDS

end = time.time()
print(end - start)

#########################
### Fold 1
#########################
[0]	validation_0-rmse:29.89377
[99]	validation_0-rmse:28.18616
#########################
### Fold 2
#########################
[0]	validation_0-rmse:29.80355
[99]	validation_0-rmse:28.07287
#########################
### Fold 3
#########################
[0]	validation_0-rmse:29.37416
[99]	validation_0-rmse:27.75877
#########################
### Fold 4
#########################
[0]	validation_0-rmse:29.07775
[99]	validation_0-rmse:27.52741
#########################
### Fold 5
#########################
[0]	validation_0-rmse:29.23411
[99]	validation_0-rmse:27.36571
#########################
### Fold 6
#########################
[0]	validation_0-rmse:29.12955
[99]	validation_0-rmse:27.39348
#########################
### Fold 7
#########################
[0]	validation_0-rmse:30.14341
[99]	validation_0-rmse:28.55944
#########################
### Fold 8
#########################
[0]	validation_0-rmse:30.69603
[99]	validation_0-rmse:28.87713
#########################
### Fold 9
#########################
[0]	validation_0-rmse:29.99158
[99]	validation_0-rmse:28.33902
#########################
### Fold 10
#########################
[0]	validation_0-rmse:29.40152
[99]	validation_0-rmse:27.66921
10.152308702468872

In [47]:
y_true = old_train_data[["ID","efs","efs_time","race_group"]].copy()
y_pred = train_data[["ID"]].copy()
y_pred["prediction"] = oof_xgb_cox
m = score(y_true.copy(), y_pred.copy(), "ID")
print(f"\nOverall CV for XGBoost Survival:Cox =",m)

Overall CV for XGBoost Survival:Cox = 0.6114712652404406

## CatBoost

In [48]:
from catboost import CatBoostRegressor, CatBoostClassifier
import catboost as cb
print("Using CatBoost version",cb.__version__)

Using CatBoost version 1.2.7

In [49]:
%%time
FOLDS = 10
kf = KFold(n_splits=FOLDS, shuffle=True, random_state=42)
    
oof_cat = np.zeros(len(train_data))
pred_cat = np.zeros(len(test_data))

for i, (train_index, test_index) in enumerate(kf.split(train_data)):

    print("#"*25)
    print(f"### Fold {i+1}")
    print("#"*25)
    
    x_train = train_data.loc[train_index,FEATURES].copy()
    y_train = train_data.loc[train_index,"y"]
    x_valid = train_data.loc[test_index,FEATURES].copy()
    y_valid = train_data.loc[test_index,"y"]
    x_test = test_data[FEATURES].copy()
 
    model_cat = CatBoostRegressor(
        bagging_temperature =  0.7954382875508031,
        border_count = 32.0,
        depth = 9.0,
        l2_leaf_reg = 5.656290326109749,
        learning_rate= 0.08337834510110963,    
        min_data_in_leaf = 39.01468374674604,
        grow_policy='Lossguide',
        random_strength = 0.6918202342914714,
        iterations = 3000.0
        #early_stopping_rounds=25,
    )
    model_cat.fit(x_train,y_train,
              eval_set=(x_valid, y_valid),
              cat_features=CATS,
              verbose=250)

    # INFER OOF
    oof_cat[test_index] = model_cat.predict(x_valid)
    # INFER TEST
    pred_cat += model_cat.predict(x_test)

# COMPUTE AVERAGE TEST PREDS
pred_cat /= FOLDS

#########################
### Fold 1
#########################
0:	learn: 0.1751711	test: 0.1766896	best: 0.1766896 (0)	total: 133ms	remaining: 6m 39s
250:	learn: 0.1485426	test: 0.1582905	best: 0.1582876 (247)	total: 18.7s	remaining: 3m 24s
500:	learn: 0.1430244	test: 0.1578962	best: 0.1578302 (428)	total: 37.7s	remaining: 3m 8s
750:	learn: 0.1389352	test: 0.1576453	best: 0.1576328 (722)	total: 56.5s	remaining: 2m 49s
1000:	learn: 0.1342638	test: 0.1576781	best: 0.1575519 (899)	total: 1m 14s	remaining: 2m 28s
1250:	learn: 0.1304494	test: 0.1577084	best: 0.1575519 (899)	total: 1m 32s	remaining: 2m 8s
1500:	learn: 0.1271073	test: 0.1578878	best: 0.1575519 (899)	total: 1m 50s	remaining: 1m 50s
1750:	learn: 0.1233600	test: 0.1577728	best: 0.1575519 (899)	total: 2m 7s	remaining: 1m 30s
2000:	learn: 0.1200375	test: 0.1578941	best: 0.1575519 (899)	total: 2m 24s	remaining: 1m 12s
2250:	learn: 0.1167443	test: 0.1580350	best: 0.1575519 (899)	total: 2m 41s	remaining: 53.9s
2500:	learn: 0.1134927	test: 0.1584737	best: 0.1575519 (899)	total: 2m 59s	remaining: 35.8s
2750:	learn: 0.1105415	test: 0.1587732	best: 0.1575519 (899)	total: 3m 16s	remaining: 17.8s
2999:	learn: 0.1072340	test: 0.1588193	best: 0.1575519 (899)	total: 3m 33s	remaining: 0us

bestTest = 0.1575518797
bestIteration = 899

Shrink model to first 900 iterations.
#########################
### Fold 2
#########################
0:	learn: 0.1755559	test: 0.1723904	best: 0.1723904 (0)	total: 96.1ms	remaining: 4m 48s
250:	learn: 0.1487379	test: 0.1538961	best: 0.1538849 (245)	total: 18.8s	remaining: 3m 25s
500:	learn: 0.1432536	test: 0.1536419	best: 0.1536153 (467)	total: 37.9s	remaining: 3m 9s
750:	learn: 0.1388694	test: 0.1536182	best: 0.1535946 (630)	total: 56.9s	remaining: 2m 50s
1000:	learn: 0.1347609	test: 0.1535389	best: 0.1535173 (991)	total: 1m 15s	remaining: 2m 30s
1250:	learn: 0.1309179	test: 0.1536383	best: 0.1534080 (1132)	total: 1m 33s	remaining: 2m 10s
1500:	learn: 0.1270645	test: 0.1537038	best: 0.1534080 (1132)	total: 1m 51s	remaining: 1m 50s
1750:	learn: 0.1237512	test: 0.1538197	best: 0.1534080 (1132)	total: 2m 8s	remaining: 1m 31s
2000:	learn: 0.1205130	test: 0.1539120	best: 0.1534080 (1132)	total: 2m 26s	remaining: 1m 13s
2250:	learn: 0.1172212	test: 0.1540376	best: 0.1534080 (1132)	total: 2m 43s	remaining: 54.4s
2500:	learn: 0.1142850	test: 0.1541846	best: 0.1534080 (1132)	total: 3m	remaining: 36.1s
2750:	learn: 0.1114612	test: 0.1544245	best: 0.1534080 (1132)	total: 3m 17s	remaining: 17.9s
2999:	learn: 0.1083232	test: 0.1546646	best: 0.1534080 (1132)	total: 3m 34s	remaining: 0us

bestTest = 0.1534079567
bestIteration = 1132

Shrink model to first 1133 iterations.
#########################
### Fold 3
#########################
0:	learn: 0.1751632	test: 0.1760900	best: 0.1760900 (0)	total: 78.7ms	remaining: 3m 55s
250:	learn: 0.1486453	test: 0.1565787	best: 0.1565787 (250)	total: 18.7s	remaining: 3m 25s
500:	learn: 0.1435912	test: 0.1558988	best: 0.1558853 (492)	total: 37.7s	remaining: 3m 8s
750:	learn: 0.1390557	test: 0.1561000	best: 0.1557954 (624)	total: 56.3s	remaining: 2m 48s
1000:	learn: 0.1348316	test: 0.1561882	best: 0.1557954 (624)	total: 1m 14s	remaining: 2m 29s
1250:	learn: 0.1311079	test: 0.1560508	best: 0.1557954 (624)	total: 1m 33s	remaining: 2m 10s
1500:	learn: 0.1275563	test: 0.1559892	best: 0.1557954 (624)	total: 1m 51s	remaining: 1m 51s
1750:	learn: 0.1236053	test: 0.1560741	best: 0.1557954 (624)	total: 2m 8s	remaining: 1m 31s
2000:	learn: 0.1201361	test: 0.1563293	best: 0.1557954 (624)	total: 2m 26s	remaining: 1m 13s
2250:	learn: 0.1167248	test: 0.1565175	best: 0.1557954 (624)	total: 2m 43s	remaining: 54.6s
2500:	learn: 0.1135650	test: 0.1567470	best: 0.1557954 (624)	total: 3m	remaining: 36.1s
2750:	learn: 0.1107849	test: 0.1569753	best: 0.1557954 (624)	total: 3m 18s	remaining: 17.9s
2999:	learn: 0.1081287	test: 0.1571395	best: 0.1557954 (624)	total: 3m 35s	remaining: 0us

bestTest = 0.1557954424
bestIteration = 624

Shrink model to first 625 iterations.
#########################
### Fold 4
#########################
0:	learn: 0.1749358	test: 0.1781408	best: 0.1781408 (0)	total: 82.9ms	remaining: 4m 8s
250:	learn: 0.1477119	test: 0.1585543	best: 0.1585496 (246)	total: 18.6s	remaining: 3m 23s
500:	learn: 0.1418544	test: 0.1581825	best: 0.1581745 (482)	total: 37.8s	remaining: 3m 8s
750:	learn: 0.1374937	test: 0.1582809	best: 0.1580909 (618)	total: 56.5s	remaining: 2m 49s
1000:	learn: 0.1334829	test: 0.1584034	best: 0.1580909 (618)	total: 1m 14s	remaining: 2m 29s
1250:	learn: 0.1296886	test: 0.1582890	best: 0.1580909 (618)	total: 1m 32s	remaining: 2m 9s
1500:	learn: 0.1260159	test: 0.1584032	best: 0.1580909 (618)	total: 1m 50s	remaining: 1m 50s
1750:	learn: 0.1224073	test: 0.1585739	best: 0.1580909 (618)	total: 2m 8s	remaining: 1m 31s
2000:	learn: 0.1189212	test: 0.1589647	best: 0.1580909 (618)	total: 2m 25s	remaining: 1m 12s
2250:	learn: 0.1159166	test: 0.1589892	best: 0.1580909 (618)	total: 2m 43s	remaining: 54.3s
2500:	learn: 0.1127128	test: 0.1594123	best: 0.1580909 (618)	total: 3m	remaining: 35.9s
2750:	learn: 0.1093742	test: 0.1597832	best: 0.1580909 (618)	total: 3m 16s	remaining: 17.8s
2999:	learn: 0.1065065	test: 0.1600426	best: 0.1580909 (618)	total: 3m 32s	remaining: 0us

bestTest = 0.1580909309
bestIteration = 618

Shrink model to first 619 iterations.
#########################
### Fold 5
#########################
0:	learn: 0.1755678	test: 0.1726947	best: 0.1726947 (0)	total: 105ms	remaining: 5m 15s
250:	learn: 0.1485121	test: 0.1557658	best: 0.1557449 (247)	total: 18.7s	remaining: 3m 25s
500:	learn: 0.1426504	test: 0.1554251	best: 0.1553763 (418)	total: 37.8s	remaining: 3m 8s
750:	learn: 0.1383626	test: 0.1554112	best: 0.1552987 (543)	total: 56.6s	remaining: 2m 49s
1000:	learn: 0.1341954	test: 0.1555547	best: 0.1552987 (543)	total: 1m 15s	remaining: 2m 30s
1250:	learn: 0.1303877	test: 0.1555446	best: 0.1552987 (543)	total: 1m 33s	remaining: 2m 10s
1500:	learn: 0.1269526	test: 0.1558509	best: 0.1552987 (543)	total: 1m 51s	remaining: 1m 51s
1750:	learn: 0.1235732	test: 0.1560859	best: 0.1552987 (543)	total: 2m 9s	remaining: 1m 32s
2000:	learn: 0.1203005	test: 0.1562729	best: 0.1552987 (543)	total: 2m 27s	remaining: 1m 13s
2250:	learn: 0.1172981	test: 0.1563294	best: 0.1552987 (543)	total: 2m 44s	remaining: 54.8s
2500:	learn: 0.1142708	test: 0.1565035	best: 0.1552987 (543)	total: 3m 1s	remaining: 36.3s
2750:	learn: 0.1111658	test: 0.1569164	best: 0.1552987 (543)	total: 3m 18s	remaining: 18s
2999:	learn: 0.1083688	test: 0.1570173	best: 0.1552987 (543)	total: 3m 35s	remaining: 0us

bestTest = 0.1552986814
bestIteration = 543

Shrink model to first 544 iterations.
#########################
### Fold 6
#########################
0:	learn: 0.1751896	test: 0.1764026	best: 0.1764026 (0)	total: 86.2ms	remaining: 4m 18s
250:	learn: 0.1482397	test: 0.1577499	best: 0.1577475 (249)	total: 18.7s	remaining: 3m 24s
500:	learn: 0.1425974	test: 0.1574252	best: 0.1573727 (466)	total: 37.8s	remaining: 3m 8s
750:	learn: 0.1377941	test: 0.1574225	best: 0.1572507 (654)	total: 56.2s	remaining: 2m 48s
1000:	learn: 0.1335241	test: 0.1576203	best: 0.1572507 (654)	total: 1m 14s	remaining: 2m 29s
1250:	learn: 0.1298891	test: 0.1578974	best: 0.1572507 (654)	total: 1m 33s	remaining: 2m 10s
1500:	learn: 0.1259647	test: 0.1583513	best: 0.1572507 (654)	total: 1m 50s	remaining: 1m 50s
1750:	learn: 0.1223395	test: 0.1587917	best: 0.1572507 (654)	total: 2m 8s	remaining: 1m 31s
2000:	learn: 0.1188114	test: 0.1591225	best: 0.1572507 (654)	total: 2m 26s	remaining: 1m 13s
2250:	learn: 0.1153234	test: 0.1593893	best: 0.1572507 (654)	total: 2m 43s	remaining: 54.4s
2500:	learn: 0.1119254	test: 0.1595145	best: 0.1572507 (654)	total: 3m	remaining: 36s
2750:	learn: 0.1085950	test: 0.1598086	best: 0.1572507 (654)	total: 3m 17s	remaining: 17.8s
2999:	learn: 0.1057212	test: 0.1600969	best: 0.1572507 (654)	total: 3m 33s	remaining: 0us

bestTest = 0.1572506816
bestIteration = 654

Shrink model to first 655 iterations.
#########################
### Fold 7
#########################
0:	learn: 0.1750030	test: 0.1773992	best: 0.1773992 (0)	total: 85.4ms	remaining: 4m 16s
250:	learn: 0.1482462	test: 0.1596206	best: 0.1596101 (240)	total: 18.5s	remaining: 3m 22s
500:	learn: 0.1425598	test: 0.1593607	best: 0.1593442 (480)	total: 37.5s	remaining: 3m 6s
750:	learn: 0.1378039	test: 0.1593832	best: 0.1592787 (683)	total: 56.3s	remaining: 2m 48s
1000:	learn: 0.1333479	test: 0.1594717	best: 0.1592352 (855)	total: 1m 14s	remaining: 2m 29s
1250:	learn: 0.1295992	test: 0.1596368	best: 0.1592352 (855)	total: 1m 33s	remaining: 2m 10s
1500:	learn: 0.1256621	test: 0.1601051	best: 0.1592352 (855)	total: 1m 50s	remaining: 1m 50s
1750:	learn: 0.1216936	test: 0.1606067	best: 0.1592352 (855)	total: 2m 8s	remaining: 1m 31s
2000:	learn: 0.1185133	test: 0.1609125	best: 0.1592352 (855)	total: 2m 25s	remaining: 1m 12s
2250:	learn: 0.1151803	test: 0.1609134	best: 0.1592352 (855)	total: 2m 43s	remaining: 54.3s
2500:	learn: 0.1117902	test: 0.1610335	best: 0.1592352 (855)	total: 2m 59s	remaining: 35.9s
2750:	learn: 0.1089327	test: 0.1612750	best: 0.1592352 (855)	total: 3m 17s	remaining: 17.8s
2999:	learn: 0.1058370	test: 0.1614187	best: 0.1592352 (855)	total: 3m 33s	remaining: 0us

bestTest = 0.1592352341
bestIteration = 855

Shrink model to first 856 iterations.
#########################
### Fold 8
#########################
0:	learn: 0.1754554	test: 0.1735899	best: 0.1735899 (0)	total: 82.6ms	remaining: 4m 7s
250:	learn: 0.1479212	test: 0.1563323	best: 0.1563289 (241)	total: 18.7s	remaining: 3m 24s
500:	learn: 0.1423906	test: 0.1559860	best: 0.1559359 (486)	total: 37.8s	remaining: 3m 8s
750:	learn: 0.1377689	test: 0.1559136	best: 0.1558485 (659)	total: 56.8s	remaining: 2m 50s
1000:	learn: 0.1334711	test: 0.1559443	best: 0.1558485 (659)	total: 1m 15s	remaining: 2m 30s
1250:	learn: 0.1293160	test: 0.1558782	best: 0.1557406 (1105)	total: 1m 33s	remaining: 2m 10s
1500:	learn: 0.1258762	test: 0.1560280	best: 0.1557406 (1105)	total: 1m 51s	remaining: 1m 50s
1750:	learn: 0.1221674	test: 0.1562945	best: 0.1557406 (1105)	total: 2m 8s	remaining: 1m 31s
2000:	learn: 0.1184733	test: 0.1564920	best: 0.1557406 (1105)	total: 2m 25s	remaining: 1m 12s
2250:	learn: 0.1152686	test: 0.1564824	best: 0.1557406 (1105)	total: 2m 43s	remaining: 54.3s
2500:	learn: 0.1118917	test: 0.1567513	best: 0.1557406 (1105)	total: 2m 59s	remaining: 35.9s
2750:	learn: 0.1084892	test: 0.1570664	best: 0.1557406 (1105)	total: 3m 16s	remaining: 17.8s
2999:	learn: 0.1053876	test: 0.1573465	best: 0.1557406 (1105)	total: 3m 32s	remaining: 0us

bestTest = 0.1557406281
bestIteration = 1105

Shrink model to first 1106 iterations.
#########################
### Fold 9
#########################
0:	learn: 0.1752348	test: 0.1755098	best: 0.1755098 (0)	total: 77.9ms	remaining: 3m 53s
250:	learn: 0.1486915	test: 0.1590715	best: 0.1590689 (247)	total: 18.9s	remaining: 3m 27s
500:	learn: 0.1433412	test: 0.1583582	best: 0.1583503 (495)	total: 38s	remaining: 3m 9s
750:	learn: 0.1389642	test: 0.1579134	best: 0.1578605 (723)	total: 57.1s	remaining: 2m 50s
1000:	learn: 0.1350866	test: 0.1580095	best: 0.1578605 (723)	total: 1m 15s	remaining: 2m 31s
1250:	learn: 0.1315784	test: 0.1580232	best: 0.1578605 (723)	total: 1m 34s	remaining: 2m 11s
1500:	learn: 0.1275437	test: 0.1578143	best: 0.1578078 (1492)	total: 1m 51s	remaining: 1m 51s
1750:	learn: 0.1237607	test: 0.1579294	best: 0.1577125 (1588)	total: 2m 9s	remaining: 1m 32s
2000:	learn: 0.1203403	test: 0.1579299	best: 0.1577125 (1588)	total: 2m 26s	remaining: 1m 13s
2250:	learn: 0.1169882	test: 0.1580500	best: 0.1577125 (1588)	total: 2m 43s	remaining: 54.4s
2500:	learn: 0.1135011	test: 0.1583921	best: 0.1577125 (1588)	total: 3m	remaining: 36s
2750:	learn: 0.1103652	test: 0.1584959	best: 0.1577125 (1588)	total: 3m 16s	remaining: 17.8s
2999:	learn: 0.1071939	test: 0.1587566	best: 0.1577125 (1588)	total: 3m 33s	remaining: 0us

bestTest = 0.1577124861
bestIteration = 1588

Shrink model to first 1589 iterations.
#########################
### Fold 10
#########################
0:	learn: 0.1753530	test: 0.1741787	best: 0.1741787 (0)	total: 74.6ms	remaining: 3m 43s
250:	learn: 0.1481683	test: 0.1570207	best: 0.1570196 (248)	total: 18.8s	remaining: 3m 25s
500:	learn: 0.1426389	test: 0.1566033	best: 0.1565375 (476)	total: 38s	remaining: 3m 9s
750:	learn: 0.1383418	test: 0.1568678	best: 0.1565375 (476)	total: 56.9s	remaining: 2m 50s
1000:	learn: 0.1339855	test: 0.1567080	best: 0.1565375 (476)	total: 1m 15s	remaining: 2m 30s
1250:	learn: 0.1300951	test: 0.1568492	best: 0.1565375 (476)	total: 1m 32s	remaining: 2m 9s
1500:	learn: 0.1265041	test: 0.1568241	best: 0.1565375 (476)	total: 1m 50s	remaining: 1m 50s
1750:	learn: 0.1228839	test: 0.1570318	best: 0.1565375 (476)	total: 2m 8s	remaining: 1m 31s
2000:	learn: 0.1194111	test: 0.1570278	best: 0.1565375 (476)	total: 2m 25s	remaining: 1m 12s
2250:	learn: 0.1159579	test: 0.1571089	best: 0.1565375 (476)	total: 2m 43s	remaining: 54.2s
2500:	learn: 0.1128994	test: 0.1572579	best: 0.1565375 (476)	total: 3m	remaining: 36s
2750:	learn: 0.1098355	test: 0.1573050	best: 0.1565375 (476)	total: 3m 16s	remaining: 17.8s
2999:	learn: 0.1070439	test: 0.1577396	best: 0.1565375 (476)	total: 3m 33s	remaining: 0us

bestTest = 0.1565375369
bestIteration = 476

Shrink model to first 477 iterations.
CPU times: user 2h 16min 19s, sys: 4min 57s, total: 2h 21min 16s
Wall time: 35min 43s

In [50]:
y_true = old_train_data[["ID","efs","efs_time","race_group"]].copy()
y_pred = train_data[["ID"]].copy()
y_pred["prediction"] = oof_cat
m = score(y_true.copy(), y_pred.copy(), "ID")
print(f"\nOverall CV for CATBoost KaplanMeier =",m)

Overall CV for CATBoost KaplanMeier = 0.6703055114270625

## RidgeRegression

In [51]:
from sklearn.linear_model import Ridge
ridge = Ridge()
param_grid_ridge = {
    'alpha': [0.05, 0.1, 1, 3, 5, 10],
    'solver': ['auto', 'svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag']
}
ridge_cv = GridSearchCV(ridge, param_grid_ridge, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)
ridge_cv.fit(X_train, train_data['y'])

GridSearchCV(cv=5, estimator=Ridge(), n_jobs=-1,
             param_grid={'alpha': [0.05, 0.1, 1, 3, 5, 10],
                         'solver': ['auto', 'svd', 'cholesky', 'lsqr',
                                    'sparse_cg', 'sag']},
             scoring='neg_mean_squared_error')

In [52]:
%%time
FOLDS = 10
kf = KFold(n_splits=FOLDS, shuffle=True, random_state=42)
    
oof_rid = np.zeros(len(train_data))
pred_rid = np.zeros(len(test_data))

for i, (train_index, test_index) in enumerate(kf.split(train_data)):

    print("#"*25)
    print(f"### Fold {i+1}")
    print("#"*25)
    
    x_train = train_data.loc[train_index,FEATURES].copy()
    y_train = train_data.loc[train_index,"y"]
    x_valid = train_data.loc[test_index,FEATURES].copy()
    y_valid = train_data.loc[test_index,"y"]
    x_test = test_data[FEATURES].copy()
 
    model_rid = Ridge(
        alpha=10, solver= 'lsqr'
    )
    model_rid.fit(x_train,y_train)

    # INFER OOF
    oof_rid[test_index] = model_rid.predict(x_valid)
    # INFER TEST
    pred_rid += model_rid.predict(x_test)

# COMPUTE AVERAGE TEST PREDS
pred_rid /= FOLDS

#########################
### Fold 1
#########################
#########################
### Fold 2
#########################
#########################
### Fold 3
#########################
#########################
### Fold 4
#########################
#########################
### Fold 5
#########################
#########################
### Fold 6
#########################
#########################
### Fold 7
#########################
#########################
### Fold 8
#########################
#########################
### Fold 9
#########################
#########################
### Fold 10
#########################
CPU times: user 1.12 s, sys: 111 ms, total: 1.23 s
Wall time: 807 ms

In [53]:
y_true = old_train_data[["ID","efs","efs_time","race_group"]].copy()
y_pred = train_data[["ID"]].copy()
y_pred["prediction"] = oof_rid
m = score(y_true.copy(), y_pred.copy(), "ID")
print(f"\nOverall CV for Ridge KaplanMeier =",m)

Overall CV for Ridge KaplanMeier = 0.6262152855045653

## Voting & Submission

In [54]:
#from scipy.stats import rankdata 

y_true = old_train_data[["ID","efs","efs_time","race_group"]].copy()
y_pred = train_data[["ID"]].copy()
y_pred["prediction"] = (oof_xgb+oof_cat+oof_lgb+0.6*oof_rid)/3.6
m = score(y_true.copy(), y_pred.copy(), "ID")
print(f"\nOverall CV for Ensemble =",m)

Overall CV for Ensemble = 0.675130357872395

In [55]:
sub = pd.read_csv("/kaggle/input/equity-post-HCT-survival-predictions/sample_submission.csv")
sub.prediction = (pred_xgb + pred_lgb+pred_cat+0.6*pred_rid)/3.6
sub.to_csv("submission.csv",index=False)
print("Sub shape:",sub.shape)
sub.head()

Sub shape: (3, 2)

      ID  prediction
0  28800    0.507624
1  28801    0.658854
2  28802    0.482659